-- return {
--   "hrsh7th/nvim-cmp",
--   lazy = false,
--   priority = 1000,
--   enabled = true,
--
--   opts = function(_, opts)
--     local cmp = require("cmp")
--
--     -- 🧠 Helper: text before cursor
--     local has_words_before = function()
--       unpack = unpack or table.unpack
--       local line, col = unpack(vim.api.nvim_win_get_cursor(0))
--       if col == 0 then
--         return false
--       end
--       local text = vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]
--       return text:sub(col, col):match("%s") == nil
--     end
--
--     ---------------------------------------------------------------------------
--     -- 🗝️  Tab/Enter mappings (safe globally)
--     ---------------------------------------------------------------------------
--     opts.mapping = cmp.mapping.preset.insert({
--       ["<Tab>"] = cmp.mapping(function(fallback)
--         if cmp.visible() then
--           cmp.select_next_item()
--         elseif has_words_before() then
--           cmp.complete()
--         else
--           fallback()
--         end
--       end, { "i", "s" }),
--
--       ["<S-Tab>"] = cmp.mapping(function(fallback)
--         if cmp.visible() then
--           cmp.select_prev_item()
--         else
--           fallback()
--         end
--       end, { "i", "s" }),
--
--       ["<CR>"] = cmp.mapping(function(fallback)
--         if cmp.visible() and cmp.get_active_entry() then
--           cmp.confirm({ select = true })
--         else
--           fallback()
--         end
--       end, { "i", "s" }),
--     })
--
--     ---------------------------------------------------------------------------
--     -- 🗂️  Load schema once
--     ---------------------------------------------------------------------------
--     local cached_schema
--     local function load_schema()
--       if cached_schema then
--         return cached_schema
--       end
--       local path = vim.fn.expand("~/.config/nvim/aspect_data/aspect_schema.json")
--       local ok, data = pcall(vim.fn.json_decode, vim.fn.readfile(path))
--       if ok and data then
--         cached_schema = data
--         return data
--       end
--       vim.notify("Failed to load ASPECT schema: " .. path, vim.log.levels.WARN)
--       return {}
--     end
--
--     ---------------------------------------------------------------------------
--     -- 🧭  Context helpers
--     ---------------------------------------------------------------------------
--     local function get_prm_context()
--       local context = {}
--       local cursor_line = vim.api.nvim_win_get_cursor(0)[1]
--       for i = cursor_line, 1, -1 do
--         local line = vim.api.nvim_buf_get_lines(0, i - 1, i, false)[1]
--         if not line then
--           break
--         end
--         local sub = line:match("^%s*subsection%s+(.+)")
--         if sub then
--           table.insert(context, 1, vim.trim(sub))
--         elseif line:match("^%s*end") then
--           break
--         end
--       end
--       return context
--     end
--
--     local function get_properties_at_path(schema, path)
--       local node = schema
--       for _, part in ipairs(path) do
--         if node.properties and node.properties[part] then
--           node = node.properties[part]
--         else
--           return {}
--         end
--       end
--       return node.properties or {}
--     end
--
--     ---------------------------------------------------------------------------
--     -- 🧩  Detect current context
--     ---------------------------------------------------------------------------
--     local function parse_current_set()
--       local line = vim.api.nvim_get_current_line()
--       -- pattern: set Something something = value
--       local key = line:match("^%s*set%s+([%w _%-]+)%s*=")
--       if key then
--         return vim.trim(key)
--       end
--       return nil
--     end
--
--     local function should_trigger_completion()
--       local line = vim.api.nvim_get_current_line()
--       local col = vim.api.nvim_win_get_cursor(0)[2]
--       local before = line:sub(1, col)
--       -- trigger if after subsection/set OR after '=' in set line
--       if before:match("[Ss][Uu][Bb][Ss][Ee][Cc][Tt][Ii][Oo][Nn]%s*$") or before:match("[Ss][Ee][Tt]%s*$") then
--         return "key"
--       elseif before:match("=") then
--         return "value"
--       end
--       return nil
--     end
--
--     ---------------------------------------------------------------------------
--     -- 🧠  Custom source
--     ---------------------------------------------------------------------------
--     cmp.register_source("aspect_prm", {
--       complete = function(_, _, callback)
--         local trigger_type = should_trigger_completion()
--         if not trigger_type then
--           return callback({ items = {}, isIncomplete = false })
--         end
--
--         local schema = load_schema()
--         local context = get_prm_context()
--         local props = get_properties_at_path(schema, context)
--
--         local items = {}
--
--         if trigger_type == "key" then
--           -- Complete parameter keys
--           for key, val in pairs(props or {}) do
--             table.insert(items, {
--               label = key,
--               kind = cmp.lsp.CompletionItemKind.Field,
--               documentation = { kind = "markdown", value = val.description or "" },
--             })
--           end
--         elseif trigger_type == "value" then
--           -- Complete parameter values (after "=")
--           local current_key = parse_current_set()
--           local key_data = props[current_key]
--           if key_data and key_data.enum then
--             for _, enum_val in ipairs(key_data.enum) do
--               table.insert(items, {
--                 label = tostring(enum_val),
--                 kind = cmp.lsp.CompletionItemKind.Value,
--                 documentation = { kind = "markdown", value = key_data.description or "" },
--               })
--             end
--           end
--         end
--
--         callback({ items = items, isIncomplete = false })
--       end,
--     })
--
--     ---------------------------------------------------------------------------
--     -- 🔧  Attach to prm filetype
--     ---------------------------------------------------------------------------
--     cmp.setup.filetype("prm", {
--       sources = cmp.config.sources(vim.list_extend(opts.sources or {}, {
--         { name = "aspect_prm", priority = 1000 },
--       })),
--     })
--
--     opts.completion = { autocomplete = { cmp.TriggerEvent.TextChanged }, debounce = 50 }
--   end,
-- }
